# Generated by Django 3.1.5 on 2021-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_auto_20210121_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='item',
            field=models.ManyToManyField(blank=True, to='receipt.Item'),
        ),
    ]
